# Generated by Django 5.0.1 on 2025-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_class_id_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('1A', '1А'), ('1B', '1Б'), ('1V', '1В'), ('1G', '1Г'), ('2A', '2А'), ('2B', '2Б'), ('2V', '2В'), ('3A', '3А'), ('3B', '3Б'), ('3V', '3В'), ('4A', '4А'), ('4B', '4Б'), ('4V', '4В'), ('5A', '5А'), ('5B', '5Б'), ('5V', '5В'), ('11A', '11А'), ('11B', '11Б'), ('11V', '11В'), ('11G', '11Г')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
