# Generated by Django 5.0.1 on 2025-05-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_classsubject_teacher_alter_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
