# Generated by Django 5.0.1 on 2025-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_classsubject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
