# Generated by Django 5.0.1 on 2025-05-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Створено'), ('updated', 'Оновлено')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
